# Generated by Django 3.2.8 on 2021-10-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='actors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='directors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='distributors')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, '스틸컷'), (2, '이후는 찾아서 적어보자')])),
                ('image', models.ImageField(upload_to='movie/images')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('running_time', models.IntegerField()),
                ('summary', models.TextField()),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('actors', models.ManyToManyField(to='movie.Actor')),
                ('directors', models.ManyToManyField(to='movie.Director')),
                ('distributors', models.ManyToManyField(to='movie.Distributor')),
                ('genres', models.ManyToManyField(to='movie.Genre')),
                ('images', models.ManyToManyField(related_name='_movie_movie_images_+', to='movie.Image')),
            ],
        ),
    ]
