# Generated by Django 3.2.9 on 2021-11-29 03:51

from django.db import migrations, models
import django.db.models.deletion
import movie.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[movie.validators.validate_score])),
                ('comment', models.TextField()),
                ('sympathy', models.IntegerField()),
                ('not_sympathy', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movie.movie')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.ManyToManyField(through='movie.Review', to='accounts.Profile'),
        ),
    ]
