# Generated by Django 3.2.9 on 2021-11-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(null=True, upload_to='movie/actors'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(null=True, upload_to='movie/directors'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='image',
            field=models.ImageField(null=True, upload_to='movie/distributors'),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.IntegerField(choices=[(1, 'Poster'), (2, 'BackDrop')]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='movie/images'),
        ),
    ]
