# Generated by Django 3.2.8 on 2021-11-01 17:32

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '가격 할인'), (2, '퍼센트 할인'), (3, '포인트 적립'), (4, '증정품 제공')])),
                ('content', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='최대 수량')),
                ('duration', models.IntegerField(verbose_name='유효 기간')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='item/%Y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='상품명')),
                ('image', models.ImageField(upload_to='item/%Y/%m', verbose_name='상품 사진')),
                ('price', models.IntegerField(verbose_name='판매가격')),
                ('is_sell', models.BooleanField(default=True, verbose_name='취소여부')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='대분류')),
            ],
        ),
        migrations.CreateModel(
            name='MiddleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='중분류')),
            ],
        ),
        migrations.CreateModel(
            name='NonCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='최대 수량')),
            ],
        ),
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, unique=True)),
                ('price', models.IntegerField(verbose_name='지불액')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='취소여부')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['RANGE'],
                'key': ['datetime'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='Order',
            name='default',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='소분류')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.maincategory', verbose_name='대분류')),
                ('middle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.middlecategory', verbose_name='중분류')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_hold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.couponhold', verbose_name='쿠폰 내역'),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item', verbose_name='상품'),
        ),
        migrations.AddField(
            model_name='order',
            name='non_coupon_hold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.noncouponhold', verbose_name='비쿠폰 내역'),
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='프로필'),
        ),
        migrations.AddField(
            model_name='noncoupon',
            name='benefit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.benefit'),
        ),
        migrations.AddField(
            model_name='noncoupon',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.event'),
        ),
        migrations.AddField(
            model_name='middlecategory',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.maincategory', verbose_name='대분류'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.subcategory', verbose_name='소분류'),
        ),
        migrations.AddField(
            model_name='event',
            name='coupon',
            field=models.ManyToManyField(related_name='_item_event_coupon_+', through='item.Coupon', to='item.Benefit'),
        ),
        migrations.AddField(
            model_name='event',
            name='non_coupon',
            field=models.ManyToManyField(related_name='_item_event_non_coupon_+', through='item.NonCoupon', to='item.Benefit'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='benefit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.benefit'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.event'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['main_category'], name='main_category_idx'),
        ),
    ]
